"use client";

/**
 * Voice mode lifecycle controller.
 *
 * In the new architecture, TTS audio is generated by the PLANNER backend
 * inline with each agent.message_segment and streamed back as
 * agent.audio_chunk events on the same SSE connection. The eventStream
 * handlers (in store/eventStream.ts) call into lib/voice.ts to play
 * chunks via Web Audio.
 *
 * So this controller's job is now just:
 *   - Cancel queued audio when voice mode toggles off
 *   - (Future) Handle voice-mode-on cleanup edge cases
 *
 * Renders nothing.
 */

import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import type { AppDispatch, RootState } from "@/store";
import { setSpeaking } from "@/store/voiceSlice";
import { cancelAllAudio } from "@/lib/voice";

export function VoicePlaybackController() {
  const dispatch = useDispatch<AppDispatch>();
  const voiceMode = useSelector((s: RootState) => s.voice.mode);

  useEffect(() => {
    if (voiceMode === "off") {
      cancelAllAudio();
      dispatch(setSpeaking(false));
    }
  }, [voiceMode, dispatch]);

  return null;
}
